services:
  db:
    image: mysql:8.0 # Specify the version as needed
    container_name: mysql-RockyRoad
    environment:
      MYSQL_DATABASE: is436
      MYSQL_USER: user # Use a non-root user
      MYSQL_PASSWORD: user_password # Set a secure password for the user
      MYSQL_ROOT_PASSWORD: root_password # Set a secure root password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/ # Mount initdb directory
    networks:
      - mysql_network # Connect to the network

volumes:
  db_data:


networks:
  mysql_network:
